#+TITLE: u/MemeInvestor_bot Documentation
#+AUTHOR: thecsw
#+DATE: <2018-05-24 Thu>
#+EMAIL: thecsw@lennarc
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://gongzhitaao.org/orgcss/org.css"/>
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:comment d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil stat:t tags:t tasks:t tex:t timestamp:t toc:t
#+OPTIONS: todo:t |:t
#+CREATOR: Emacs 25.3.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* *Welcome to Meme Investment!*

Welcome to the source code page of u/MemeInvestor_bot! Nice to meet you. First
of all, let me talk you through what the bot does and details later. Quick note,
if you want to contribute, do so! Check the TODO list and help the Meme
Investments thrive! /Thanks!/

** The duty

This bot has been developed exclusively for r/MemeEconomy. It can create
investment account, help invest and then automatically return calculated
investment 4 hours after the investment. To calculate the investment return, the bot
multiplies the invested amount by a power function of the form *y = Ax^m*,
where *A* and *m* are constants (*A=0.17366* , *m=0.2527*) and *x* is the change in upvotes
on the post since the invesment was made. This function was written to emulate/replace
the block of if/else statements that was originally used to calculate the investment return.
The overall behavior of the function is a steep rise towards the break-even threshold (y=1)
between 1020 and 1021 upvotes, and levelling off towards higher upvote changes. 
There is also an upper cap imposed on the function at 750,000 upvotes with a max multiplier of approximately
5.30063 times the original investment. Any gain in upvotes at or above this cap will recieve this maximum multiplier. 

Currently, it has 8 commands:

+ !create - creates a bank account for you with a new balance of 1000
  MemeCoins.
+ !invest AMOUNT - invests AMOUNT in the meme (post). 4 hours after the
  investment, the meme growth will be evaluated and your investment can profit
  you or make you bankrupt. Minimum possible investment is 100 MemeCoins.
+ !balance - returns your current balance.
+ !active - returns a number of active investments.
+ !broke - only if your balance is less than 100 MemeCoins and you do not have
  any active investments, declares bankruptcy on your account and sets your
  balance to 100 MemeCoins (minimum possible investment). 
+ !market - gives an overview for the whole Meme market.
+ !ignore - ignores the whole message.
+ !help - returns this help message.

To invoke any command, type it in the comment sections of r/MemeEconomy

* Getting started 

These instructions will get you a copy of the project up and running on your
local machine for development and testing purposes. See deployment for notes on
how to deploy the project on a live system. 

* Prerequisites

#+BEGIN_SRC shell
sudo pip3 install praw
#+END_SRC

OR

#+BEGIN_SRC shell
sudo pip3 install --upgrade -r requirements.txt
#+END_SRC

1. [[https://github.com/praw-dev/praw][praw]] is Python Reddit API Wrapper. This will be the main and only package to
   connect to Reddit's API and extract desired data.

* Installing and configuring

The only thing that needs to be done before execution is the config. The only
thing that needs to be done before execution is the config profile. In the
config profile you should fill your Reddit API details.

For that please follow the steps below

#+BEGIN_SRC shell
git clone https://github.com/thecsw/memeinvestor_bot
cd memeinvestor_bot
mv example.config.py config.py
nano config.py
#+END_SRC

After filling out the details, save and exit. You're done with installation.

* Deployment

Remove the word **'example'** from the title of all files with it.

Just run this

#+BEGIN_SRC shell
python3 main.py
#+END_SRC

It is time to make a fortune!

* Source code

I will post an update to the source code later!

* Built With
 1. [[https://github.com/praw-dev/praw][praw]] is Python Reddit API Wrapper. This will be the main and only package to
    connect to Reddit's API and extract desired data.

* Authors
 - *Sagindyk Urazayev* - /Initial work and SQL Rewrite/ - [[https://github.com/thecsw][thecsw]]
 - *jimbobur* - /Heavy additions to investment logic/ - [[https://github.com/jimbobur][jimbobur]]
 - *ggppjj* - /Minor Fixes/ - [[https://github.com/ggppjj][ggppjj]]
 - *rickles42* - /Minor Fixes/ - [[https://github.com/rickles42][rickles42]]

* License

This project is licensed under the The GNU General Public License (see the
[[https://github.com/thecsw/prequelmemes_bot/blob/master/LICENSE][LICENSE.md]] file for details), it explains everything pretty well. 

* Todo list

This is going to be a short todo list. If you have the true loyalty and some
free time, try to add/fix the following todo items or add your own with the
issues tab or push.

** TODO

** DONE
