FROM alpine

RUN apk add --update --no-cache \
    bash \
    curl

RUN mkdir /caddy

RUN curl https://getcaddy.com | bash -s personal http.cors

WORKDIR /caddy

EXPOSE 80 443 2015
VOLUME [ "/caddy" ]

CMD [ "caddy" ]