FROM golang:1.12.5-alpine3.9

RUN apk add --no-cache \
			git

RUN adduser -D appuser
USER appuser
WORKDIR /home/appuser

RUN go get -u github.com/jinzhu/gorm
RUN go get github.com/lib/pq
RUN go get github.com/thecsw/mira

COPY . .

RUN go build -o exec ./bot

CMD [ "./exec" ]